/oak:
  ros__parameters:
    pipeline_gen:
      i_nn_type: none
      i_pipeline_type: Stereo
      i_enable_imu: true
    left:
      i_publish_topic: true
      i_board_socket_id: 1  # CAM_B - OV9782
      i_fps: 30.0
      i_width: 1280
      i_height: 800
      i_synced: true
    right:
      i_publish_topic: true
      i_board_socket_id: 2  # CAM_C - OV9782
      i_fps: 30.0
      i_width: 1280
      i_height: 800
      i_synced: true
    imu:
      i_batch_report_threshold: 1
      i_max_batch_reports: 10
      i_acc_freq: 200
      i_gyro_freq: 200
      i_sync_method: "LINEAR_INTERPOLATE_ACCEL"
